apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: ${IMAGE_REPOSITORY}
  tagPolicy:
    inputDigest: {}
manifests:
  helm:
    releases:
      - name: ${CHART_NAME}
        chartPath: chart
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO}}"
          image.tag: "{{.IMAGE_TAG}}"
deploy:
  helm: {}
