# https://taskfile.dev

version: "3"

vars:
  VERSION: 0.0.1

tasks:
  run: go run -ldflags "-X main.version={{.VERSION}}" .
  build: go build -ldflags "-X main.version={{.VERSION}}" .
  install: go build -ldflags "-X main.version=$(version)" -o /usr/local/bin/devkit .

  push-images:
    cmds:
      - task: push-code-image
      - task: push-elastic-image
      - task: push-grafana-image
      - task: push-jenkins-image
      - task: push-mailtrap-image
      - task: push-unleash-image
      - task: push-template-images

  push-code-image:
    dir: helpers/loop-code
    vars:
      DOCKER_IMAGE: adrianliechti/loop-code
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .

  push-elastic-image:
    dir: helpers/loop-elastic
    vars:
      DOCKER_IMAGE: adrianliechti/loop-elastic
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .

  push-grafana-image:
    dir: helpers/loop-grafana
    vars:
      DOCKER_IMAGE: adrianliechti/loop-grafana
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .

  push-jenkins-image:
    dir: helpers/loop-jenkins
    vars:
      DOCKER_IMAGE: adrianliechti/loop-jenkins
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} helpers/loop-jenkins -f helpers/loop-jenkins/Dockerfile .
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}}:dind helpers/loop-jenkins-dind -f helpers/loop-jenkins-dind/Dockerfile .

  push-mailtrap-image:
    dir: helpers/loop-mailtrap
    vars:
      DOCKER_IMAGE: adrianliechti/loop-mailtrap
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .

  push-unleash-image:
    dir: helpers/loop-unleash
    vars:
      DOCKER_IMAGE: adrianliechti/loop-unleash
    cmds:
      - docker buildx build --push --platform linux/arm64,linux/amd64 --tag {{.DOCKER_IMAGE}} .

  push-template-images:
    cmds:
      - task: push-template-image
        vars: { STACK: angular }
      - task: push-template-image
        vars: { STACK: aspnet }
      - task: push-template-image
        vars: { STACK: golang }
      - task: push-template-image
        vars: { STACK: nginx }
      - task: push-template-image
        vars: { STACK: pack }
      - task: push-template-image
        vars: { STACK: python }
      - task: push-template-image
        vars: { STACK: react }
      - task: push-template-image
        vars: { STACK: spring }

  push-template-image:
    dir: helpers/loop-template/{{.STACK}}
    vars:
      DOCKER_IMAGE: adrianliechti/loop-template:{{.STACK}}
    cmds:
      - docker build . --tag {{.DOCKER_IMAGE}} --platform linux/amd64
      - docker push {{.DOCKER_IMAGE}}
