apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    isDefault: true
    editable: false

  - name: Tempo
    type: tempo
    access: proxy
    url: http://localhost:3200
    editable: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    editable: false
