#! /bin/bash -e

rsync -au $JENKINS_REF/ $JENKINS_HOME/

java_opts_array=()

while IFS= read -r -d '' item; do
  java_opts_array+=( "$item" )
done < <([[ $JAVA_OPTS ]] && xargs printf '%s\0' <<<"$JAVA_OPTS")

jenkins_opts_array=()

while IFS= read -r -d '' item; do
  jenkins_opts_array+=( "$item" )
done < <([[ $JENKINS_OPTS ]] && xargs printf '%s\0' <<<"$JENKINS_OPTS")

exec java -Duser.home="$JENKINS_HOME" "${java_opts_array[@]}" -jar /usr/share/jenkins/jenkins.war "${jenkins_opts_array[@]}" "$@"